# Generated by Django 5.1 on 2024-08-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('numeroTelefonico', models.TextField(db_column='numero_telefonico')),
                ('password', models.TextField()),
                ('tipoUsuario', models.TextField(choices=[('NOVIO', 'NOVIO'), ('INVITADO', 'INVITADO'), ('ADMIN', 'ADMIN')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
