# Generated by Django 5.1 on 2024-08-23 01:40

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_modifique_nombre_columna_tabla_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaNovio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.UUIDField(default=uuid.uuid4)),
                ('novia', models.ForeignKey(db_column='novia_id', on_delete=django.db.models.deletion.RESTRICT, related_name='usuario_novia', to=settings.AUTH_USER_MODEL)),
                ('novio', models.ForeignKey(db_column='novio_id', on_delete=django.db.models.deletion.RESTRICT, related_name='usuario_novio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lista_novios',
            },
        ),
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('url', models.URLField()),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('ubicacion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('habilitado', models.BooleanField(default=True)),
                ('listaNovio', models.ForeignKey(db_column='lista_novios_id', on_delete=django.db.models.deletion.RESTRICT, to='gestion.listanovio')),
            ],
            options={
                'db_table': 'regalos',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updateAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('regalo', models.ForeignKey(db_column='regalo_id', on_delete=django.db.models.deletion.RESTRICT, to='gestion.regalo')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservaciones',
            },
        ),
    ]
