# Generated by Django 5.1 on 2024-08-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_creacion_tablas_lista_novios_regalos_y_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
