"""agregue tabla productos

Revision ID: 825bdc7ac5f0
Revises: bca3a92f69d2
Create Date: 2024-07-26 22:53:57.619899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825bdc7ac5f0'
down_revision = 'bca3a92f69d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
